package exception;

public class ExceptionHandling {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
//		try {
//			System.out.println("1");
//			
//		int a=9/0;
//		System.out.println("2");
// 
//	}
//		catch(ArithmeticException e)
//		{
//			System.out.println("3");
//			}
//		catch(Exception e) {
//			System.out.println("4");
//			 
//		}
//		
//		finally {
//			System.out.println("5");
//			 
//		}
//		ExceptionHandling eh = new ExceptionHandling();
//		eh.m1();
//	}

//	private void m1() {
//		// TODO Auto-generated method stub
//		m2();
//		System.out.println("1");
//	}

//	private void m2() {
//		// TODO Auto-generated method stub
//		m3();
//		System.out.println("2");
//	}
//
//	private void m3() {
//		// TODO Auto-generated method stub
//		System.out.println("3");
//	
//	try {
//		int b = 3/0;
//		System.out.println("4");
//		
//}
//	catch (ArithmeticException e)
//	{   System.out.println(e.getMessage());
//		System.out.println("5");
//	}
//	{
//		System.out.println("6");
//	}
}
}